### ISSUE TITLE
No clear indication that `collection_names` is needed

### ISSUE THREAD

**Issue by beef331** [sci-comp/SceneBuilder#1]
Instead of https://github.com/sci-comp/SceneBuilder/blob/df73d54d0b370f17766e548b655f0d65b7fa7b07/scene_builder_dock.gd#L693 it likely should create the file or prompt the user with a dialog of "Would you like to create ....".

**Comment by sci-comp** [comment]
Great suggestion! We now simply create the CollectionNames resource if one does not exist.

Change is included in commit: https://github.com/sci-comp/SceneBuilder/commit/dafd2daff3aba481d07f5868affa012dc299a97a
