### ISSUE TITLE
Suggestion of improvements

### ISSUE THREAD

**Issue by smedelyan** [sci-comp/SceneBuilder#18]
Hi. I'd like to suggest the following improvements to be implemented. I believe this is doable and will really improve user experience a lot.

## Configurable data folder

**Improvement:** Allow to configure data folder with a default of `res://Data/...`
**Motivation:** Projects may have their own policy for file system structure and naming. It would be great not to invade or make users change it, but instead adapt to whatever is there.

**Implementation options (how this can be done?)**
1. As a project setting 
2. As a static `SceneBuilderConfig` class with static methods like `set_data_folder`. These methods then can be called from a user's autoload on project load.

## Simplify management of collections

**Improvement**
Get rid of special resource `collection_names.tres`. Just parse the subdirectories of the data directory and interpret each of them as category. This implies that there's no need to have exactly 12 buttons in the dock. If user uses only 2-3 - let's display just them. If user needs 20 categories - let's display them all (possibly, with a scroll). I don't believe that the current way of swapping collection names is convenient, it should be easier. Also, it's weird to have empty buttons for a "not set"-categories, they just occupy space

**Motivation**
It's just too complicated. As you mention in the readme, the current way is not the best or ideal one.

## Simplify item resource (*.tres)

**Improvement**
Keep everything needed for an item in single resource file. `thumbnail` can be just `Texture2D` field in it

**Motivation**
Creating subfolders `Item` and `Thumbnail` is neither convenient nor necessary. It can be simpler

## Remove thumbnail restrictions

**Improvement**
Scale thumbnail so that it fits the right size.

**Motivation**
I haven't looked at the implementation of SceneBuilder, but Godot has powerful tools for GUI, so we can make use of any source data, (e.g. use `STRETCH_KEEP_ASPECT_CENTERED` for a `TextureRect`) no need to restrict that to 80x80 size.

## Keep track of scenes

**Improvement**
Track scenes uid along with paths. This should help to identify scenes even if they moved to a different place

**Motivation**
The user now lacks the right for a mistake. They must decide the location of their assets once and forever (or suffer from manually editing paths, or use some find-and-replace / grep / sed magic). I'm not sure whether Godot exposes API to find a Resource by uid, but if it does, this should do the trick. If it doesn't, it is doable to introduce your own "uid-holder" as a quick-fix

------

Of course, these changes will require to migrate user's current layout to a new one, so maybe another action should be exposed or run semi-automatically

**Comment by smedelyan** [comment]
Ideally, with the above implemented, the user will do the following simple steps to setup & create their first item:
1. Install plugin
2. Create data folder (or set their own)
3. Create subdirectory ( = category)
4. Create 1 `Chair.tres` resource, set a (optional) thumbnail, a scene, maybe something else
5. That's it. (maybe at this step they will also need to hit "Reload" button somewhere, but better investigate whether it's possible to subscribe to something like "new files created" within Editor)

**Comment by sci-comp** [comment]
@smedelyan 

Oh wow, what wonderful feedback. I must have missed an email, I'm sorry that I'm just now seeing this!

I believe I agree with everything you're saying here. The only reason things were done as they are (eg, 12 static buttons) was because the approach looked easy to implement and I wanted to get things working quickly.

I'm swamped this week, but I'll try to address these suggestions throughout the month!

Thank you so much for giving this a look!

**Comment by smedelyan** [comment]
That's damn great!!! Thank you so much! ❤️ 🐳 🤖

**Comment by sci-comp** [comment]
Thank you as well! Posts like your really help get things done. 

I've probably introduced a few bugs here, I'll be testing things throughout the week. Also, I'll try to make the fence tool nicer to use next, I still haven't fully thought out how that needs to work.
