### ISSUE TITLE
No explanation of the requirement of the scene

### ISSUE THREAD

**Issue by beef331** [sci-comp/SceneBuilder#2]
Presently if the user makes a new scene there is no indication of what the scene needs (CollisionShape and StaticBody) just an error message of "Failed to instantiate item, raycast missed" when trying to place things.

**Comment by sci-comp** [comment]
Good catch! We now print a normal message, since it's not really an error,

> Raycast missed, items must be instantiated on a StaticBody with a CollisionShape

Change is included in commit: https://github.com/sci-comp/SceneBuilder/commit/dafd2daff3aba481d07f5868affa012dc299a97a
