### ISSUE TITLE
Shortcuts overlap with default Godot shortcuts

### ISSUE THREAD

**Issue by beef331** [sci-comp/SceneBuilder#3]
Shift + scrollwheel moves through placeables but also zooms in the Godot scene camera.

**Comment by sci-comp** [comment]
I was hoping that I'd figure out how to disable the viewport zoom while shift is pressed, but I haven't found any hints on how to solve that problem. 

I will simply find new keys for selecting the next/previous item for now.

**Comment by sci-comp** [comment]
We can now,

- Select previous/next items by pressing: Shift + Left/Right Arrow
- Select previous/next category by pressing: Alt + Left/Right Arrow

If anyone happens to see this in the future and knows how to disable viewport camera zooming, please let me know!

**Comment by beef331** [comment]
`InputEvent`  has https://docs.godotengine.org/en/stable/classes/class_control.html#class-control-method-accept-event which you might be able to use to consume events before the window gets them? I don't know just guessing.

**Comment by sci-comp** [comment]
That method is part of the Control class, which we don't use for input at editor time.

Instead, I think we should be able to use: `forward_3d_gui_input` with `return EditorPlugin.AFTER_GUI_INPUT_STOP`, but it doesn't work for me.

https://docs.godotengine.org/en/stable/classes/class_editorplugin.html#class-editorplugin-private-method-forward-3d-gui-input
