### ISSUE TITLE
Alt-shortcuts don't work

### ISSUE THREAD

**Issue by Zondartul** [sci-comp/SceneBuilder#9]
Using Godot v4.2.2
Addon is installed as res:://addons/SceneBuilder/
Problem: attempting to use any alt-shortcut (e.g., alt+P) results in the error:
`res://addons/SceneBuilder/scene_builder_commands.gd:31 - Invalid get index 'alphabetize_nodes' (on base: 'GDScript').`
This is fixed if you make the following change in scene_builder_plugin.gd on line 17:
from
`scene_builder_input_map = load("res://addons/SceneBuilder/scene_builder_input_map.gd")`
to
`scene_builder_input_map = load("res://addons/SceneBuilder/scene_builder_input_map.gd").new()`

**Comment by sci-comp** [comment]
Thank you so much! We should be loading the resource `scene_builder_input_map.tres` instead of the script `scene_builder_input_map.gd` here.
